apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: appofapp-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: prometheus
    namespace: appofapp-argocd
  project: appofapp
  source:
    helm:
      valueFiles:
        - values.yaml
    path: "charts/prometheus"
    repoURL: "https://github.com/MaxRBosch/argocd-test"
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2